// Copyright 2026 Federico Runco (federico.runco@gmail.com)
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
// 
// Licensed under the Solderpad Hardware License v2.1 (the “License”); 
// you may not use this file except in compliance with the License, or, 
// at your option, the Apache License version 2.0. You may obtain a copy 
// of the License at https://solderpad.org/licenses/SHL-2.1/
// 
// Unless required by applicable law or agreed to in writing, any work 
// distributed under the License is distributed on an “AS IS” BASIS, WITHOUT 
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
// License for the specific language governing permissions and limitations 
// under the License.

module baud_gen #(
	parameter int clk_freq = 50000000,
	// Autogenerated parameter, DO NOT CHANGE
	parameter int w = $clog2(clk_freq-1) 
) (
	input	logic			clk_i,
	input	logic 			rst_ni,
	input	logic[w-1:0] 	divider_i,
	output	logic			tick_o,
	output	logic			tick8_o
);

	logic [w-1:0]	cnt16;
    logic [3:0]		cnt_baud;

	always_ff @ (posedge clk_i) begin
		if (!rst_ni) begin
			cnt16    <= '0;
			cnt_baud <= '0;
			tick8_o <= 1'b0;
            tick_o   <= 1'b0;
        end else begin
            tick8_o <= 1'b0;
            tick_o   <= 1'b0;

            if (cnt16 == divider_i) begin
                cnt16    <= '0;
                tick8_o <= 1'b1;
                
                if (cnt_baud == 4'd15) begin
                    cnt_baud <= '0;
                    tick_o   <= 1'b1;
                end else begin
                    cnt_baud <= cnt_baud + 1;
                end
            end else begin
                cnt16 <= cnt16 + 1'b1;
            end
        end
    end

endmodule