# Copyright 2026 Federico Runco (federico.runco@gmail.com)
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
# 
# Licensed under the Solderpad Hardware License v2.1 (the “License”); 
# you may not use this file except in compliance with the License, or, 
# at your option, the Apache License version 2.0. You may obtain a copy 
# of the License at https://solderpad.org/licenses/SHL-2.1/
# 
# Unless required by applicable law or agreed to in writing, any work 
# distributed under the License is distributed on an “AS IS” BASIS, WITHOUT 
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
# License for the specific language governing permissions and limitations 
# under the License.

import argparse
from pathlib import Path

def main():
	parser = argparse.ArgumentParser(description="BootROM generator")
	parser.add_argument("--input", required=True, help="Input HEX file")
	parser.add_argument("--output", required=True, help="Output SystemVerilog file")
	args = parser.parse_args()

	in_path = Path(args.input)
	out_path = Path(args.output)

	rom_contents = str()
	with in_path.open("r", encoding="utf-8") as f:
		lines = f.readlines()
		lines = [line.rstrip('\n') for line in lines]
		for i, line in enumerate(lines):
			if len(line) == 16:
				if i == len(lines) - 1:
					rom_contents += f"\t\t64'h{line[:8]}_{line[8:]}"
				else:
					rom_contents += f"\t\t64'h{line[:8]}_{line[8:]},\n"
			else:
				print("ERROR")

	rom_indexes = len(lines)

	with out_path.open("w", encoding="utf-8") as f:
		f.write(f"""// Copyright 2026 Federico Runco (federico.runco@gmail.com)
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
// 
// Licensed under the Solderpad Hardware License v2.1 (the “License”); 
// you may not use this file except in compliance with the License, or, 
// at your option, the Apache License version 2.0. You may obtain a copy 
// of the License at https://solderpad.org/licenses/SHL-2.1/
// 
// Unless required by applicable law or agreed to in writing, any work 
// distributed under the License is distributed on an “AS IS” BASIS, WITHOUT 
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
// License for the specific language governing permissions and limitations 
// under the License.
		  
// ----------------------------------------------------------
// | STOP: Autogenerated file - Do not Touch, use makefile! |
// ----------------------------------------------------------

module bootrom (
	input 	logic 			clk_i,
	input 	logic 			req_i,
	input 	logic [63:0] 	addr_i,
	output 	logic [63:0] 	data_o
); 
		  
	localparam int size = {rom_indexes};

    const logic [0:size-1][63:0] data = {{
{rom_contents}
	}};

	logic [$clog2(size)-1:0] addr;

    always_ff @(posedge clk_i) begin
        if (req_i) begin
            addr <= addr_i[$clog2(size)-1+3:3];
        end
    end

    assign data_o = (addr < size) ? data[addr] : '0;

endmodule
		""")

if __name__ == "__main__":
	main()